eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# datasource
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:investments
    username: sa
    password: 

# jpa
spring: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update

# h2
spring:
  h2: 
   console:
    enabled: true
    path: /h2-console
